language: csharp
matrix:
  include:
    - name: "Windows"
      os: windows
      language: shell
      env: PATH=/c/Program Files (x86)/MSBuild/14.0/Bin:$PATH
script: msbuild /p:Configuration=Release'
notifications:
  email: false
