language: csharp
matrix:
  include:
    - name: "Windows"
      os: windows
      language: shell
script: "C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" /p:Configuration=Release
notifications:
  email: false
