version: 0.0
os: windows
files:
  - source: /publish
    destination: C:/aws-ci-cd-101    
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.ps1
  AfterInstall:
    - location: scripts/AfterInstall.ps1
  ApplicationStart:
    - location: scripts/ApplicationStart.ps1
