version: 0.2

env:
  variables:
    SOLUTION: .\AwsCICD101.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.8
    TEST_DLL: .\test\AwsCICD101.Test\bin\Release\AwsCICD101.Test.dll
    VSTEST_EXE: .\packages\Microsoft.TestPlatform.16.2.0\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe

phases:
  build:
    commands:
      - 'nuget restore'
      - 'msbuild /p:Configuration=Release'
      - 'vstest.console "${env:TEST_DLL}"'
artifacts:
  files:
    - .\src\AwsCICD101\bin\Release\*
