version: 0.2

env:
  variables:
    SOLUTION: .\AwsCICD101.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.8
    TEST_DLL: .\test\AwsCICD101.Test\bin\Release\AwsCICD101.Test.dll

phases:
  pre_build:
    commands:
      - 'nuget restore'
  build:
    commands:
      - 'msbuild /p:Configuration=Release'
  post_build:
    commands:
      - 'vstest.console "${env:TEST_DLL}"'
      - 'msbuild /p:Configuration=Release /t:Publish .\src\AwsCICD101.Web\AwsCICD101.Web.csproj'
      - 'Copy-Item -Recurse -Force .\src\AwsCICD101.Web\obj\Release\Package\PackageTmp .\publish'
artifacts:
  files:
    - .\publish\*
    - .\appspec.yml

