version: 0.2

env:
  variables:
    SOLUTION: .\AwsCICD101.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.8
    TEST_DLL: .\test\AwsCICD101.Test\bin\Release\AwsCICD101.Test.dll

phases:
  pre_build:
    commands:
      - 'nuget restore'
  build:
    commands:
      - 'msbuild /p:Configuration=Release'
  post_build:
    commands:
      - 'vstest.console "${env:TEST_DLL}"'
artifacts:
  files:
    - .\src\AwsCICD101\bin\Release\*
